theme: jekyll-theme-cayman
title: Who is Ryota OZAKI?
github:
  is_project_page: false
description: <a href= "https://forms.gle/YhKBErhBd8Qm8pt46" target="_blank" >[Contact Me]</a>
headerLinks:
  - title: GitHub
    url: https://github.com/kaodim/android-design
buttons:
  btn1_url: https://github.com/UsergeTeam/Userge
  btn1_title: Main Repository
